spring.application.name=backend
# 1. Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_estagio_db
spring.datasource.username=postgres
spring.datasource.password=root

# 2. Driver de conexão
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Comportamento do Hibernate / JPA
# 'update' faz o Spring validar e sincronizar as classes Java com as tabelas do banco
spring.jpa.hibernate.ddl-auto=update

# 4. Exibir as consultas SQL no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true